### ISSUE TITLE
Hitting return in new measure popup closes the popup without adding the new measure

### ISSUE THREAD

**Issue by christopherswenson** [malloydata/malloy-composer#26] opened 2022-11-14 20:35 UTC
First seen by @tschomer. I haven't tried to reproduce exactly yet. He tried to save one with no name, got an error, added a name, then hit enter (while focused in the name input).

**Comment by whscullin** [comment] 2022-11-14 21:42
We're using `<form>` elements to wrap all our form-like dialogs, but `<form>` has a specific meaning, and the result is the return key in a text field will attempt to submit the form, and we get "Form submission canceled because the form is not connected" in the console. We may not want to use `<form>`, or we need to handle `onSubmit()` and have it do something meaningful.

**Comment by whscullin** [comment] 2022-11-14 21:55
@tschomer - Is the expected behavior when return is hit to close the dialog, or do we want to require explicitly clicking/tabbing to hitting enter on the Save button?

**Comment by tschomer** [comment] 2022-11-15 19:31
i think if you're in a field that doesn't accept pressing return to create a new line/paragraph that it acts as the Save button. typing Return/Enter now just closes the popover and doesn't make a new measure. feels kinda broken.

**Comment by christopherswenson** [comment] 2022-11-16 02:47
I used form elements specifically so that pressing enter in a field would trigger a form submit action that would be equivalent to hitting the done button. So we could

A) decide that hitting enter in a field to submit is not functionality we want
B) manually deal with the enter key on every form element
C) figure out some way to handle this error (`event.preventDefault`?)

**Comment by whscullin** [comment] 2022-11-16 17:53
The underlying issue is that `<button>`s are by default `type="submit" so every `<button>` needs to either explicitly be declared `type="button"`, or `onClick(event) => { event.preventDefault() }` to avoid accidental form submissions. So that's fixed for now but remains a potential trip-wire.

**Comment by whscullin** [comment] 2022-11-16 17:53
Fixed with https://github.com/malloydata/malloy-composer/pull/38

**Closed by whscullin** 2022-11-16 17:53 UTC
