### ISSUE TITLE
Show progress spinner when navigating from a read me to a query

### ISSUE THREAD

**Issue by tschomer** [malloydata/malloy-composer#35] opened 2022-11-16 02:07 UTC
It's quite slow to load when you click a saved query on a read me. Lets show a progress spinner in the body of the page when you do so.

**Comment by whscullin** [comment] 2022-11-17 21:39
Duplicate of https://github.com/malloydata/malloy-composer/issues/50

**Closed by whscullin** 2022-11-17 21:39 UTC
Labels: enhancement
